#region

using System.Reflection;

#endregion

namespace Pristar4.ChessEngine;

public static class VersionInfo {
    /// <summary>
    ///     GetProjectVersion returns the version of the project.
    ///     It uses the GitVersionInformation class to get the version.
    ///     which is generated by GitVersion. and injected into the project.
    /// </summary>
    /// <param name="includeDate"></param>
    /// <returns>
    ///     The version of the project.
    /// </returns>
    public static string GetProjectVersion(bool includeDate = true) {
        var assembly = Assembly.GetExecutingAssembly();
        var gitVersionInformationType = assembly.GetType("GitVersionInformation");
        if (gitVersionInformationType == null)
            return "Unknown";
        var version = gitVersionInformationType.GetField("FullSemVer")?.GetValue(null);
        return includeDate ? version + " build " + GetBuildDate() : version as string ?? "Unknown";

        string? GetBuildDate()
        {
            return gitVersionInformationType.GetField("CommitDate")?.GetValue(null) as string;
        }
    }

   
}