#region

using System.Reflection;

#endregion

namespace QuickBot;

public static class VersionInfo {
    /// <summary>
    ///     GetProjectVersion returns the version of the project.
    ///     It uses the GitVersionInformation class to get the version.
    ///     which is generated by GitVersion. and injected into the project.
    /// </summary>
    /// <returns>
    ///     The version of the project.
    /// </returns>
    public static string GetProjectVersion() {
        var assembly = Assembly.GetExecutingAssembly();
        var gitVersionInformationType = assembly.GetType("GitVersionInformation");
        if (gitVersionInformationType == null)
            return "Unknown";
        object? version = gitVersionInformationType.GetField("FullSemVer")?.GetValue(null);
        return version + " build " +
               gitVersionInformationType.GetField("CommitDate")?.GetValue(null);
    }
}